### ISSUE TITLE
No module named 'viz_tools'

### ISSUE THREAD

**Issue by zhufeng888** [qiqihaer/3DSSD-pytorch-openPCDet#1]
Your job hels me a lot. but when I run 
`python train.py`
it reminds me that
`Traceback (most recent call last):
  File "train.py", line 6, in <module>
    from test import repeat_eval_ckpt
  File "/home/hby/hdd/chenyanbin/3DSSD-pytorch-openPCDet/tools/test.py", line 13, in <module>
    from eval_utils import eval_utils
  File "/home/hby/hdd/chenyanbin/3DSSD-pytorch-openPCDet/tools/eval_utils/eval_utils.py", line 8, in <module>
    from pcdet.models import load_data_to_gpu
  File "/home/hby/hdd/chenyanbin/3DSSD-pytorch-openPCDet/pcdet/models/__init__.py", line 6, in <module>
    from .detectors import build_detector
  File "/home/hby/hdd/chenyanbin/3DSSD-pytorch-openPCDet/pcdet/models/detectors/__init__.py", line 1, in <module>
    from .detector3d_template import Detector3DTemplate
  File "/home/hby/hdd/chenyanbin/3DSSD-pytorch-openPCDet/pcdet/models/detectors/detector3d_template.py", line 7, in <module>
    from .. import backbones_2d, backbones_3d, dense_heads, roi_heads
  File "/home/hby/hdd/chenyanbin/3DSSD-pytorch-openPCDet/pcdet/models/backbones_3d/__init__.py", line 1, in <module>
    from .pointnet2_backbone import PointNet2Backbone, PointNet2MSG
  File "/home/hby/hdd/chenyanbin/3DSSD-pytorch-openPCDet/pcdet/models/backbones_3d/pointnet2_backbone.py", line 8, in <module>
    from viz_tools.viz_utils import point_viz
ModuleNotFoundError: No module named 'viz_tools'
`
and the github don't have the folder viz_tools. Could you help me ?
Thank you very much.

**Comment by zhufeng888** [comment]
the folder maybe your self-folder for visualing results. I delete it and re-run., but the spconv1.2 may not work normly. I'm try to reinstall spconv1.0.

**Comment by zhufeng888** [comment]
I canceled loading related code about spconv, and it runs great. Thanks again.

**Comment by qiqihaer** [comment]
Please comment out the viz_tools or the viz_utils. This is just for debugging.
