### ISSUE TITLE
ninja: build stopped: subcommand failed.

### ISSUE THREAD

**Issue by BigPig117** [qiqihaer/3DSSD-pytorch-openPCDet#10]
I compiled 3dssd on the installed pcdet 0.5.2 
An error occurred after run setup.py:

ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/xxx/anaconda3/envs/xx/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1673, in _run_ninja_build
    env=env)
  File "/home/xxx/anaconda3/envs/xx/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 22, in <module>
    cmdclass={'build_ext': BuildExtension}
  File "/home/xxx/anaconda3/envs/xx/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/xxx/anaconda3/envs/xx/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/xxx/anaconda3/envs/xx/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/xxx/anaconda3/envs/xx/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/xxx/anaconda3/envs/xx/lib/python3.7/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/home/xxx/anaconda3/envs/xx/lib/python3.7/site-packages/setuptools/command/develop.py", line 114, in install_for_development
    self.run_command('build_ext')
  File "/home/xxx/anaconda3/envs/xxj/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/xxx/anaconda3/envs/xx/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/xxx/anaconda3/envs/xx/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/xxx/anaconda3/envs/xx/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/xxx/anaconda3/envs/xx/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 708, in build_extensions
    build_ext.build_extensions(self)
  File "/home/xxx/anaconda3/envs/xx/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/xxx/anaconda3/envs/xx/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/xxx/anaconda3/envs/xx/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/xxx/anaconda3/envs/xx/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/home/xxx/anaconda3/envs/xx/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 538, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/xxx/anaconda3/envs/xx/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1359, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/xxx/anaconda3/envs/xx/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1683, in _run_ninja_build
    raise RuntimeError(message) from e

appreciate it if you could give me some advice

**Comment by ajithvcoder** [comment]
@BigPig117 were you able to solve it
