### ISSUE TITLE
Getting error when i run python setup.py develop 

### ISSUE THREAD

**Issue by ajithvcoder** [qiqihaer/3DSSD-pytorch-openPCDet#12]
Getting following error when i run `python setup.py develop` in `pcdet/ops/pointnet2/pointnet2_3DSSD` folder
```
running develop
/home/mcw/anaconda3/envs/3dssd/lib/python3.8/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/home/mcw/anaconda3/envs/3dssd/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running egg_info
writing pointnet2_3DSSD.egg-info/PKG-INFO
writing dependency_links to pointnet2_3DSSD.egg-info/dependency_links.txt
writing top-level names to pointnet2_3DSSD.egg-info/top_level.txt
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    setup(
  File "/home/mcw/anaconda3/envs/3dssd/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/mcw/anaconda3/envs/3dssd/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/mcw/anaconda3/envs/3dssd/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/mcw/anaconda3/envs/3dssd/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/mcw/anaconda3/envs/3dssd/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/mcw/anaconda3/envs/3dssd/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/mcw/anaconda3/envs/3dssd/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/home/mcw/anaconda3/envs/3dssd/lib/python3.8/site-packages/setuptools/command/develop.py", line 110, in install_for_development
    self.run_command('egg_info')
  File "/home/mcw/anaconda3/envs/3dssd/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/mcw/anaconda3/envs/3dssd/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/mcw/anaconda3/envs/3dssd/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/mcw/anaconda3/envs/3dssd/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 308, in run
    self.find_sources()
  File "/home/mcw/anaconda3/envs/3dssd/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 316, in find_sources
    mm.run()
  File "/home/mcw/anaconda3/envs/3dssd/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 560, in run
    self.add_defaults()
  File "/home/mcw/anaconda3/envs/3dssd/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 597, in add_defaults
    sdist.add_defaults(self)
  File "/home/mcw/anaconda3/envs/3dssd/lib/python3.8/site-packages/setuptools/command/sdist.py", line 106, in add_defaults
    super().add_defaults()
  File "/home/mcw/anaconda3/envs/3dssd/lib/python3.8/site-packages/setuptools/_distutils/command/sdist.py", line 252, in add_defaults
    self._add_defaults_ext()
  File "/home/mcw/anaconda3/envs/3dssd/lib/python3.8/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
    build_ext = self.get_finalized_command('build_ext')
  File "/home/mcw/anaconda3/envs/3dssd/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 304, in get_finalized_command
    cmd_obj = self.distribution.get_command_obj(command, create)
  File "/home/mcw/anaconda3/envs/3dssd/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 861, in get_command_obj
    cmd_obj = self.command_obj[command] = klass(self)
  File "/home/mcw/anaconda3/envs/3dssd/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 351, in __init__
    if not is_ninja_available():
  File "/home/mcw/anaconda3/envs/3dssd/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1310, in is_ninja_available
    subprocess.check_call('ninja --version'.split(), stdout=devnull)
  File "/home/mcw/anaconda3/envs/3dssd/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ninja', '--version']' returned non-zero exit status 245.
```

**Comment by 3623687277** [comment]
same error，any answers?
