### ISSUE TITLE
The error when I run train.py

### ISSUE THREAD

**Issue by RichardF168** [qiqihaer/3DSSD-pytorch-openPCDet#2]
when I run train.py under tools, I encounter this error. I wonder how to solve this.

Traceback (most recent call last):
  File "train.py", line 198, in <module>
    main()
  File "train.py", line 112, in main
    total_epochs=args.epochs
  File "/home/yifan/Code/OpenPCDet/pcdet/datasets/__init__.py", line 51, in build_dataloader
    logger=logger,
  File "/home/yifan/Code/OpenPCDet/pcdet/datasets/kitti/kitti_dataset.py", line 23, in __init__
    dataset_cfg=dataset_cfg, class_names=class_names, training=training, root_path=root_path, logger=logger
  File "/home/yifan/Code/OpenPCDet/pcdet/datasets/dataset.py", line 32, in __init__
    ) if self.training else None
  File "/home/yifan/Code/OpenPCDet/pcdet/datasets/augmentor/data_augmentor.py", line 23, in __init__
    cur_augmentor = getattr(self, cur_cfg.NAME)(config=cur_cfg)
  File "/home/yifan/Code/OpenPCDet/pcdet/datasets/augmentor/data_augmentor.py", line 31, in gt_sampling
    logger=self.logger
  File "/home/yifan/Code/OpenPCDet/pcdet/datasets/augmentor/database_sampler.py", line 21, in __init__
    with open(str(db_info_path), 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/yifan/Code/SESS/3DSSD-pytorch-openPCDet-main/data/kitti/kitti_dbinfos_train.pkl'

Does anyone have any idea?

**Comment by qiqihaer** [comment]
Please follow the instructions of OpenPCDet to prepare the KITTI's data
